# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux) user login shell
#   - (Windows) powershell
shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -s alacritty

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    #family: monospace
    family: Fira Code

    # The `style` can be specified to pick a specific face.
    style: Light

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Fira Code

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Victor Mono

    # The `style` can be specified to pick a specific face.
    style: Italic Light

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Victor Mono

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 14.0
