export ASDF_DATA_DIR="~/.local/share/asdf"

[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.bash ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.bash

eval "$(fzf --bash)"

eval "$(starship init bash)"
