" What a funny comment character
" .gvimrc
" v 0.5

" Focus follows mouse
" set mousefocus

" Turns on the tab bar always
set showtabline=2

" Number of horizontal lines on the screen
set lines=60

" GUI Option to remove the Toolbar (T)
set guioptions-=T

if has('macunix')
  " Sets the font and size
  set guifont=Iosevka-Term-Thin:h14

  " Sets the percent transparency
  set transparency=7

  let g:fzf_launcher = "osascript ~/.vim/macvim_fzf.scpt %s \"\$PWD\""

elseif has('unix')

  set guifont=Inconsolata\ Medium\ 12

elseif has('win32')

  set guifont=Consolas:h10:cANSI

endif

" Auto load files that have local changes
set autoread

" Make command enter make a new line without splitting
inoremap <D-CR> <ESC>o

" Command-][ to increase/decrease indentation
nnoremap <D-]> >>
nnoremap <D-[> <<
vnoremap <D-]> >>
vnoremap <D-[> <<
