#!/usr/bin/env zsh

list=(http://github.com/mileszs/ack.vim.git
http://github.com/Raimondi/delimitMate.git
git://github.com/scrooloose/nerdcommenter.git
git://github.com/scrooloose/nerdtree.git
http://github.com/csexton/rvm.vim.git
http://github.com/msanders/snipmate.vim.git
http://github.com/ervandew/supertab.git
http://github.com/tpope/vim-abolish.git
http://github.com/tpope/vim-fugitive.git
git://github.com/tpope/vim-rails.git
git://github.com/astashov/vim-ruby-debugger.git
http://github.com/vim-ruby/vim-ruby.git
http://github.com/tpope/vim-surround.git
git://github.com/tpope/vim-unimpaired.git)

mkdir -p bundle
cd bundle
for url in $list
do
  git clone $url
done
