format = "$fill$all$line_break$character"
right_format = "$directory"

[character]
success_symbol = "[\uf054](bold blue)"
error_symbol = "[\uf054](bold red)"
vicmd_symbol = "[\uea65](green)"

[git_status]
disabled = true

[package]
display_private = true

[directory]
style = "inverted"
read_only_style = "inverted"
format = "\ue0b6[$path ]($style)[$read_only]($read_only_style)"

[git_branch]
format = "[$symbol$branch]($style) "

[cmd_duration]
disabled = true

[fill]
symbol = " "

[env_var.BASE16_THEME]
format = "\u2497 $env_value "

[vagrant]
disabled = true
