format = "$fill $all$directory$line_break$character"

[character]
success_symbol = "[○](bold blue)"
error_symbol = "[◉](bold red)"
vicmd_symbol = "[◌](blue)"

[git_status]
disabled = true

[package]
display_private = true

[directory]
style = "inverted"
format = "\ue0b6[$path ]($style)[$read_only]($read_only_style)"

[git_branch]
format = "[$symbol$branch]($style) "

[cmd_duration]
format = "⏱️[$duration]($style) "
show_notifications = true

[fill]
symbol = " "

[env_var.BASE16_THEME]
format="\u246F$env_value "

[vagrant]
disabled = true
