format = "$fill $all| [ $directory](inverted)$line_break$character"

[character]
success_symbol = "[○](bold blue)"
error_symbol = "[◉](bold red)"
vicmd_symbol = "[◌](blue)"

[git_status]
disabled = true

[package]
display_private = true

[directory]
style = "inverted"

[git_branch]
format = "[$symbol$branch]($style) "

[cmd_duration]
format = "⏱️[$duration]($style) "
show_notifications = true

[fill]
symbol = " "

[env_var.BASE16_THEME]
format="[16](inverted bold)[ $env_value ](inverted bright-black) "
