[font]
size = 14.0

[font.bold]
family = "Fira Code"
style = "Regular"

[font.bold_italic]
family = "Victor Mono"
style = "Bold Italic"

[font.italic]
family = "Victor Mono"
style = "Italic Light"

[font.normal]
family = "Fira Code"
style = "Light"

[selection]
save_to_clipboard = true

[shell]
args = ["-c", "/usr/local/bin/abduco -A alacritty /usr/local/bin/nvim"]
program = "/usr/local/bin/fish"
