theme = "onedark"

[editor]
color-modes = true
cursorline = true
auto-save = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
